theme: plainwhite-jekyll

plainwhite:
  name: Thiyagarajan Karuppaiah
  tagline: Techi. Athlete
  date_format: "%b %-d, %Y"
  disqus_shortname: Thiyagu

  social_links:
    twitter: 2mrt
    github:  thiyaguin
    linkedIn: in/2thiyagu

markdown: kramdown
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
